ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;

CREATE TABLE accounts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR2(20) NOT NULL UNIQUE,
    holder_name VARCHAR2(100) NOT NULL,
    balance NUMBER(15,2) DEFAULT 0,
    currency VARCHAR2(3) DEFAULT 'TND',
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO accounts (account_number, holder_name, balance, currency, status)
SELECT
    'ACC-' || LPAD(LEVEL, 4, '0'),
    'Client ' || LEVEL,
    ROUND(DBMS_RANDOM.VALUE(1000, 51000), 2),
    CASE WHEN DBMS_RANDOM.VALUE(0,1) < 0.7 THEN 'TND' ELSE 'EUR' END,
    CASE WHEN DBMS_RANDOM.VALUE(0,1) < 0.95 THEN 'ACTIVE' ELSE 'BLOCKED' END
FROM dual CONNECT BY LEVEL <= 200;

CREATE TABLE transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account VARCHAR2(20) NOT NULL,
    target_account VARCHAR2(20) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'TND',
    status VARCHAR2(20) DEFAULT 'SUCCESS',
    type VARCHAR2(30) DEFAULT 'TRANSFER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO transactions (source_account, target_account, amount, currency, status, type, created_at)
SELECT
    'ACC-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1, 201)), 4, '0'),
    'ACC-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1, 201)), 4, '0'),
    ROUND(DBMS_RANDOM.VALUE(10, 5010), 2),
    'TND',
    'SUCCESS',
    'TRANSFER',
    CURRENT_TIMESTAMP - DBMS_RANDOM.VALUE(0, 0.5)
FROM dual CONNECT BY LEVEL <= 487;

CREATE TABLE batch_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    run_date DATE DEFAULT TRUNC(SYSDATE),
    records_processed NUMBER DEFAULT 0,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    error_message VARCHAR2(500)
);

INSERT INTO batch_log (job_name, status, run_date, records_processed, started_at, finished_at, error_message)
VALUES ('DAILY_SYNC', 'FAILED', TRUNC(SYSDATE), 487, CURRENT_TIMESTAMP - INTERVAL '6' HOUR, CURRENT_TIMESTAMP - INTERVAL '5' HOUR, 'Connection timeout after 487 records - 13 records lost');

INSERT INTO batch_log (job_name, status, run_date, records_processed, started_at, finished_at)
VALUES ('BALANCE_SNAPSHOT', 'SUCCESS', TRUNC(SYSDATE), 200, CURRENT_TIMESTAMP - INTERVAL '5' HOUR, CURRENT_TIMESTAMP - INTERVAL '4' HOUR);

CREATE TABLE account_balances (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER NOT NULL,
    balance_date DATE DEFAULT TRUNC(SYSDATE),
    closing_balance NUMBER(15,2) NOT NULL,
    transaction_count NUMBER DEFAULT 0
);

INSERT INTO account_balances (account_id, balance_date, closing_balance, transaction_count)
SELECT
    LEVEL,
    TRUNC(SYSDATE),
    ROUND(DBMS_RANDOM.VALUE(1000, 51000), 2),
    FLOOR(DBMS_RANDOM.VALUE(0, 10))
FROM dual CONNECT BY LEVEL <= 200;

COMMIT;